/*
 * apiConfiguration.h
 *
 *  Created on: Mar 26, 2020
 *      Author: jonas
 */

#ifndef INC_APICONFIGURATION_H_
#define INC_APICONFIGURATION_H_

#define API_MEMORY_SIZE 512

#define API_STATE_JOYDRIVE 0x0000

#define API_INSTRUCTION_READ 0x02
#define API_INSTRUCTION_WRITE 0x04

#define API_ERROR_WRONG_FORMAT 0x0000
#define API_ERROR_INVALID_ADDRESS 0x0001
#define API_ERROR_WRONG_INSTRUCTOR 0x0002
#define API_ERROR_ACCESS_DENIED 0x0003

#define API_REG_STATE 0x0000

#define API_REG_PWMLEFT 0x0002
#define API_REG_PWMRIGHT 0x000

#define API_BENCH_LIDAR_START 0x000f
#define API_BENCH_LIDAR_END API_BENCH_LIDAR_START + 360

#define API_REG_HEADING_KVH 0x0178

#endif /* INC_APICONFIGURATION_H_ */
